### ISSUE TITLE
Adding Homebrew's zsh functions to module

### ISSUE THREAD

**Issue by rtgibbons** [zimfw/homebrew#5]
Homebrew install's all the ZSH functions for applications installed info /opt/homebrew/share/zsh/site-functions by default using `$(brew --prefix)/share/zsh/site-functions` to get the exact path. 

Should `fpath+="$(brew --prefix)/share/zsh/site-functions"` be added after the `brew` availability check to add these functions in? Or is there a better way?

**Comment by ericbn** [comment]
Hi @rtgibbons.

I get `/usr/local/share/zsh/site-functions` -- which is the fpath you mention -- out-of-the-box in macOS in a fresh Zsh shell:
```
% cd ${$(mktemp -d):A}
% touch .zshrc
% ZDOTDIR=${PWD} HOME=${PWD} exec zsh
% print ${fpath}
/usr/local/share/zsh/site-functions /usr/local/Cellar/zsh/5.9/share/zsh/functions
%
```
The above uses Zsh installed via Homebrew. I also get that fpath in the Zsh provided by macOS. Just the `exec zsh` step changes:
```
% cd ${$(mktemp -d):A}
% touch .zshrc
% ZDOTDIR=${PWD} HOME=${PWD} exec /bin/zsh
% print ${fpath}
/usr/local/share/zsh/site-functions /usr/share/zsh/site-functions /usr/share/zsh/5.8.1/functions
%
```

**Comment by rtgibbons** [comment]
Maybe this is a Apple Silicon thing? My `brew --prefix` is /opt/homebrew. When installing apps e.g. Heroku, it's putting their autocomplete functions in `/opt/homebrew/share/zsh/site-functions` which isn't included in what you shared above.

Once I added the above fpath addition , then it picked up the homebrew auto completions (via https://docs.brew.sh/Shell-Completion)

**Comment by ericbn** [comment]
Maybe we can check: if `/opt/homebrew/share/zsh/site-functions` exists and it's not in fpath, then add it to fpath. Will this work for you?

Taking into consideration other "non-standard" prefixes that different installations of homebrew can use, I've come up with this:
```zsh
fpath+=(/opt/homebrew/share/zsh/site-functions(N) /home/linuxbrew/.linuxbrew/share/zsh/site-functions(N))
```

**Comment by rtgibbons** [comment]
I think that's a great idea to include the others. Let me know if you need anything else from me.
